### ISSUE TITLE
Darkest Dungeon Backup not working

### ISSUE THREAD

**Issue by maxbla** [supremesonicbrazil/GBML#42]
### System
Arch linux on x86_64.

### Problem
GBML mistakenly backs up config file when it should back up savegame file for darkest dungeon.

### Potential Fix
Revised entry in DB.ods for darkest dungeon:
`262060 | Darkest Dungeon | DarkestDungeon | $STEAMUSER/262060/remote | remote | ~/.local/share/Red Hook Studios/Darkest | Darkest | [N/A] | [N/A] | [N/A] | [N/A] | [N/A] | [N/A] | [N/A] | [N/A]` The old entry had other errors, such as using $STEAMAPPS instead of $STEAMUSER in SavePath1.

I would like to be able to make small changes like this in the future. May I have write access to this repository?

**Comment by supremesonicbrazil** [comment]
Moved to GitLab: https://gitlab.com/supremesonicbrazil/GBML/issues/42
