### ISSUE TITLE
Backups overwriting upon second backup

### ISSUE THREAD

**Issue by maxbla** [supremesonicbrazil/GBML#43]
Currently, when one backs up a savegame, then plays, creating a new savefile, then backs it up again, GBML overwrites the previous savegame backup. In the short term, GBML should issue a warning before overwriting a backup. In the long term, it would be loveley to see some version control. It could be as simple as creating separate folders with the date and time for each backup of a game to live in, or as complicated as viewing each file to see if it has changed and only backing up the changed files (differential backups). I personally favor the first approach, as it is much easier to implement and game saves are rarely large enough to worry about. What do you think?

**Comment by supremesonicbrazil** [comment]
Moved to GitLab: https://gitlab.com/supremesonicbrazil/GBML/issues/43
