### ISSUE TITLE
Refactor or Rewrite

### ISSUE THREAD

**Issue by maxbla** [supremesonicbrazil/GBML#44]
I wish to help with a rewrite or refactor of this code. 
### Rewrite
For a rewrite, you mentioned using Python in contributing.md. I think Python would be an excellent choice, as this application is probably mostly I/O bound, so python probably wouldn't slow it down and python is much quicker for me to write and debug. I know python pretty well and I'd love to help in the porting process. It would probably be a ton of work though. Note: some of the refactor work mentioned below would apply to a python version as well.
### Refactor
This code needs some style guidelines. Google's [C++ Style Guide](https://google.github.io/styleguide/cppguide.html) is pretty well regarded and I think it would be a great place to start. Some of the major changes that would accompany this is an 80 character line limit (there's some flexability there, see [here](https://google.github.io/styleguide/cppguide.html#Formatting)), two space indent, and variable naming [see here](https://google.github.io/styleguide/cppguide.html#Naming). I am very familiar with c and moderately familiar with C++ and would be able to help this refactor effort. I haven't used Qt before, so you would need to help with that. I would like to somehow eliminate the current database system through refactoring, although I am not sure exactly how. One option is to use an in memory hash map to store file locations. This would not use excessive RAM, as the current csv file is 647kB and GBML currently uses ~20MB of RAM when I use it. I would also like to split this app up into a command line interface and a GUI. You might wonder why someone with a gaming PC would want a command line interface and my only answer is data recovery. Even if it had no use though, it would be a challenge that would force us to organize the code in a way that makes sense.

My vote is for a refactor for now, but I'm curious what others think.

**Comment by supremesonicbrazil** [comment]
Moved to GitLab: https://gitlab.com/supremesonicbrazil/GBML/issues/44
